Community:
  type: entity
  table: community
  fields:
    trackId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: track_id
      generator:
        strategy: IDENTITY
    playCount:
      type: smallint
      nullable: true
      column: play_count
  lifecycleCallbacks: {  }
