Radio\MainBundle\Entity\Track:
  type: entity
  table: track
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    filename:
      type: string
      length: 255
      fixed: false
      nullable: false
    name:
      type: string
      length: 255
      fixed: false
      nullable: true
    artist:
      type: string
      length: 255
      fixed: false
      nullable: true
    time:
      type: string
      length: 10
      fixed: false
      nullable: true
    genre:
      type: string
      length: 45
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
